# -*- coding: utf-8 -*-
"""LSTM_Decoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQVtG1aNwVe_9pVX_kXY07fwOcGEKD-9
"""

import torch
import torch.nn as nn

class LSTMDecoder(nn.Module):

    def __init__(self, vocab_size, embed_size, hidden_size, num_layers=1):
        super(LSTMDecoder, self).__init__()

        self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embed_size)
        self.dropout = nn.Dropout(p=0.1)

        # Concatenated input size = embedding + encoder output (both have size 128 -> multiply by 2)
        lstm_input_size = embed_size*2

        self.lstm = nn.LSTM(input_size=lstm_input_size, hidden_size=hidden_size, num_layers=num_layers, batch_first=True)
        self.fc_out = nn.Linear(in_features=hidden_size, out_features=vocab_size) #this is done to put the vector back
        #to the form of probability vector -> choose the one with the highest probability

    def forward(self, encoder_output, input_seq):
        """
        input_seq:      (batch_size, seq_len)
        encoder_output: (batch_size, embed_dim)
        """
        input_seq = input_seq.long()
        B, T = input_seq.shape
        embedded = self.dropout(self.embedding(input_seq))  # (batch_size, seq_len, embed_dim)

        # Repeat encoder output at each time step
        encoder_expanded = encoder_output.unsqueeze(1).repeat(1, T, 1)  # (batch_size, seq_len, embed_dim)

        # Concatenate token embedding with encoder features
        lstm_input = torch.cat([embedded, encoder_expanded], dim=2)  # (batch_size, seq_len, 2 * embed_dim)

        output, _ = self.lstm(lstm_input)  # (batch_size, seq_len, embed_dim)
        output = self.fc_out(output)       # (batch_size, seq_len, vocab_size)
        return output