# -*- coding: utf-8 -*-
"""Text_Decoder_and_Model_Evaluation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GrWF4ELAkcPgvQJJn28zQBNe2C3l__c
"""

import torch
import torch.nn.functional as F

def beam_search(model, images, sos_id, eos_id, pad_id, max_seq_len = max_seq_len, beam_size: int = 5, length_norm = True):
  model.eval()

  batch_size = images.shape[0]

  # Reshape images (batch_size, channel, height, width)
  images = images.unsqueeze(1) # (batch_size, 1, channel, height, width)
  images = images.repeat(1, beam_size, 1, 1, 1) # (batch_size, beam_size, channel, height, width)
  images = images.view(batch_size * beam_size, *images.shape[2:]) # (batch * beam, channel, height, width)

  device = next(model.parameters()).device
  images = images.to(device)

  # Initialize beams
  seqs = torch.full((batch_size * beam_size, 1), sos_id, dtype = torch.long, device = device) #(batch * beam, 1)
  scores = torch.zeros(batch_size * beam_size, dtype = torch.float, device = device) # (batch * beam, )
  finished = torch.zeros(batch_size * beam_size, dtype = torch.bool, device = device) # (batch * beam, )

  # Mask to identify each beam belongs to which image
  beam_indices = (torch.arange(batch_size, dtype = torch.long, device = device).unsqueeze(1).repeat(1, beam_size).view(-1) * beam_size) # (batch * beam, )

  # Beam search loop
  for t in range(max_seq_len):
    logits = model(images, seqs)
    logits = logits[:,-1,:]
    ''' [Take all batch,
        take the last time step token,
        take all the vocab] '''
    log_probs = F.log_softmax(logits, dim = -1)

    # Stop expansion beams when reach <eos>
    log_probs[finished] = -1e9        # -1e9 ~ -infinity
    log_probs[finished, eos_id] = 0

    # Expand beams per image
    scores_ = scores.view(batch_size, beam_size, 1)
    log_probs = log_probs.view(batch_size, beam_size, -1)

    total_scores = scores_ + log_probs  # (batch_size, beam_size, vocab_size)

    # Select top k seq per image
    total_scores = total_scores.view(batch_size, -1)
    top_scores, top_ids = torch.topk(total_scores, k = beam_size, largest = True, dim = 1)

    vocab_size = log_probs.size(-1)

    # Which old beam was chosen
    beam_ids = top_ids // log_probs.size(-1)
    # Which new token was chosen
    token_ids = top_ids % log_probs.size(-1)

    # Convert to global indices
    beam_ids = beam_ids + beam_indices.view(batch_size, beam_size)

    beam_ids = beam_ids.view(-1)
    token_ids = token_ids.view(-1)

    # Update sequences
    seqs = torch.cat([seqs[beam_ids], token_ids.unsqueeze(1)], dim = 1)

    scores = top_scores.view(-1)
    finished = finished[beam_ids] | (token_ids == eos_id)

    # Early stopping
    if finished.view(batch_size, beam_size).all():
      break

  # Length normalization
  if length_norm:
    lengths = (seqs!= pad_id).sum(dim=1) -1
    scores = scores / lengths.clamp(min = 1)

  # Select best beam per image
  scores = scores.view(batch_size, beam_size)
  seqs = seqs.view(batch_size, beam_size, -1)

  best_ids = torch.argmax(scores, dim = 1)
  best_seqs = seqs[torch.arange(batch_size), best_ids]

  # Remove <sos> and <eos>
  result = []
  for seq in best_seqs.tolist():
    if seq[0] == sos_id:
      seq = seq[1:]
    if eos_id in seq:
      seq = seq[:seq.index(eos_id)]
    result.append(seq)

  return result

def decode_text(token_ids_batch, vocab):
  """
  Decode a batch of token IDs into tokens and strings.

  Args:
        token_ids_batch: list of lists OR 1D list of token IDs
        vocab: vocabulary object with `lookup_token(id)`

  Returns:
        decoded_tokens_list: list of list of tokens
        decoded_texts: list of strings
  """
  # If single sequence, wrap it in a list
  if isinstance(token_ids_batch[0], int):
    token_ids_batch = [token_ids_batch]

  decoded_tokens = []
  decoded_texts = []

  for token_ids in token_ids_batch:
    tokens = []
    for idx in token_ids:
      try:
        token = vocab.lookup_token(idx)
        if token == '<sos>' or token == '<eos>' or token == '<pad>':
          continue
      except IndexError:
        token = '<unk>'
      tokens.append(token)

    decoded_tokens.append(tokens)
    decoded_texts.append(' '.join(tokens))

  return decoded_tokens, decoded_texts

def evaluate_model(model, test_loader, vocab, max_seq_len, beam_size=5):
    model.eval()
    device = next(model.parameters()).device

    true_sequences_tokens = []
    true_sequences_latex = []
    predicted_sequences_tokens = []
    predicted_sequences_latex = []

    with torch.no_grad():
      for images, true_latex_ids in test_loader:
          images = images.to(device)

          # Decode true sequences
          true_tokens_batch, true_latex_batch = decode_text(true_latex_ids.tolist(), vocab)
          true_sequences_tokens.extend(true_tokens_batch)
          true_sequences_latex.extend(true_latex_batch)

          # Predict sequences
          pred_tokens_batch = beam_search(
                model,
                images,
                sos_id = vocab['<sos>'],
                eos_id = vocab['<eos>'],
                pad_id = vocab['<pad>'],
                max_seq_len = max_seq_len,
                beam_size = beam_size
            )

          # Decode predicted sequences
          pred_tokens_decoded, pred_latex_decoded = decode_text(pred_tokens_batch, vocab)
          predicted_sequences_tokens.extend(pred_tokens_decoded)
          predicted_sequences_latex.extend(pred_latex_decoded)

    return true_sequences_tokens, true_sequences_latex, predicted_sequences_tokens, predicted_sequences_latex